### ISSUE TITLE
pe2loaddata fails if an image file is missing

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/pe2loaddata#7]
Fails when not all files listed in the XML file can be found in the image directory. Its probably better to issue a warning but continue.

Error:

```
ubuntu@ip-10-0-3-123:~/efs/2017_03_08_neutrophile_migration_becker/workspace/software/cellpainting_scripts$ ./create_csv_from_xml.sh -b ${BATCH_ID} --plate ${PLATE_ID}
get_plate_dir_from_id
SQ00015167__2016-04-21T03_34_00-Measurement1
[Thu Mar 23 18:56:23 UTC 2017] creating csv for SQ00015167__2016-04-21T03_34_00-Measurement1
[Thu Mar 23 18:56:24 UTC 2017] /home/ubuntu/efs/2017_03_08_neutrophile_migration_becker/workspace/load_data_csv/2016_04_01_a549_48hr_batch1/SQ00015167__2016-04-21T03_34_00-Measurement1/load_data.csv exists.
Overwrite? (Y/N)Y
Traceback (most recent call last):
  File "/home/ubuntu/efs/2017_03_08_neutrophile_migration_becker/workspace/software/pe2loaddata/pe2loaddata.py", line 318, in <module>
    main()
  File "/home/ubuntu/efs/2017_03_08_neutrophile_migration_becker/workspace/software/pe2loaddata/pe2loaddata.py", line 267, in main
    write_csv(writer, images, plates, wells, channels, metadata, paths)
  File "/home/ubuntu/efs/2017_03_08_neutrophile_migration_becker/workspace/software/pe2loaddata/pe2loaddata.py", line 311, in write_csv
    row += [file_name, paths[file_name]]
KeyError: u'r06c11f09p01-ch1sk1fk1fl1.tiff'
ubuntu@ip-10-0-3-123:~/efs/2017_03_08_neutrophile_migration_becker/workspace/software/cellpainting_scripts$
```

**Comment by shntnu** [comment]
Looks like this is being handled correctly after all. I wasn't able to reproduce the error above

https://github.com/broadinstitute/pe2loaddata/blob/6d20dffafe55d4199ea1645c0b1080bc13945a4a/pe2loaddata.py#L306-L318
